version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./uploads:/var/www/html/uploads
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_NAME=kamateraho
      - DB_USER=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kamateraho
    volumes:
      - db_data:/var/lib/mysql
      - ./database/kamateraho.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db_data: